### ISSUE TITLE
Add Wallet Features

### ISSUE THREAD

**Issue by super3** [Storj/farmer-gui#118]
Currently we require the user to use can external wallet to receive rewards. This complicates the process, and might make it difficult to do advanced payment features like microchannels/micropayments. 

- [ ] Implement signed and verified binaries
- [ ] @boshevski Prototype wallet design
- [ ] Implement wallet design
- [ ] Hook up design to external wallet API/dependency

**Comment by super3** [comment]
I have doubts about if we should be implementing a wallet at all. It increases the complexity of the code x10.

**Comment by gordonwritescode** [comment]
I'm going to close this since it's not on the roadmap and I agree that we should not direct any effort towards this in the near future.
