### ISSUE TITLE
Improve tray icon

### ISSUE THREAD

**Issue by super3** [Storj/farmer-gui#161]
Be nice to have a clearer tray icon.

**Comment by super3** [comment]
![tray](https://cloud.githubusercontent.com/assets/60975/12237833/b7dc901a-b84e-11e5-8245-9ef8ad918ad0.png)

**Comment by pvdl** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/1476340/14942325/8779f7b0-0fb9-11e6-909b-58b8f81dd59f.png)

Version 0.7.4 has no transparent background

**Comment by littleskunk** [comment]
JeremyPepper2 commented 6 hours ago

<img width="177" alt="92171302-10b7-11e6-806d-7dbcef6a2e8f" src="https://cloud.githubusercontent.com/assets/6333390/14979096/82ab2cf0-1120-11e6-96f4-f44be76ed0dc.png">

As you can see, the tray icon is not displaying well. It is not only slightly blurry (already reported - for Windows I believe), but also too big for a tray icon in OS X.

**Comment by boshevski** [comment]
Tray icon images are already added, what's left is to add the code for handling multiple tray images.
Check here: http://electron.rocks/proper-tray-icon/

**Comment by littleskunk** [comment]
Fixed with the next version (0.7.5). Reopen the issue if you think the tray icon could be better.
