### ISSUE TITLE
Removing data functionality

### ISSUE THREAD

**Issue by boshevski** [Storj/farmer-gui#174]
Reducing the storage allocation does not remove the data from the drive. Also there is no option to remove all data from the system. Here is what we can do:

- [ ] Check storage usage and update the data allocation on **START**.
- [ ] Add **Remove All Data** button with confirmation in preferences.

**Comment by littleskunk** [comment]
We can delete only the last shards. That way we don't have to remove all data. This solution must be implemented in dataserv-client. It is possible but maybe not usefull for the final release. Your decision.

**Comment by WilhelmGGW** [comment]
Seems to me this is should be an important feature, especially with more and more folks coming on to test and use DriveShare. I'm a competent computer user - probably more than most folks - but I have over-committed available disk space more times than I'd like to admit, on my four computers. Each time I've had to manually delete all the contents of my storage data directory and start all over again with a smaller drive allocation. If I've done this, I can imagine it happening with other folks.. translating to a ton of bandwidth waste, downloading, deleting, and re-downloading all new shards.

Seems to me the user should be able to make adjustments by just changing the Storage Size in the GUI. This already works for increasing the storage size; i.e., if I set the size at 20 GB, and it downloads that much data, I can stop the client, increase the size to 40 GB and the extra 20 GB will load up to the now 40 GB limit. What I'm suggesting is just the reverse of this.. for lopping off small increments of storage when one has set the limit too high.

**Comment by gordonwritescode** [comment]
We need to take into consideration the effect this will have on a production system in that if you resize your space or delete data, renter data will be lost and the associated storage contract will be terminated. 

We will need a pretty smart algorithm to do determine which contracts have or will have the lowest yield during their lifespan and account for differences in the audit/payment schedule between these contracts.

@jamesp something to think about.

**Comment by gordonwritescode** [comment]
This is no longer relevant as expired contracts will have their associated shards reaped on an interval and now that we are farming "live" data we do not want to encourage farmers to abandon their contracts.
