### ISSUE TITLE
Large memory usage in windows

### ISSUE THREAD

**Issue by zoro1** [Storj/farmer-gui#180]
One instance of Driveshare gui (as is shown in the capture) increases its memory usage over time!
Observed under windows 7 64b. I am running driveshare with 2 seperate disks but i see 3 instances of the gui and the one of them is 'huge'. 
image capture link:
http://imgur.com/s0lGepJ

**Comment by littleskunk** [comment]
I bet it is the log. We hold it in memory. If driveshare-gui crashes (I know it should not) we loose the log and are unable to fix the problem. A real logfile would be better.

**Comment by gordonwritescode** [comment]
This bug was submitted long before the we replaced the entire engine, so I'm closing it. If it persists, please feel free to reopen.
