### ISSUE TITLE
Confusing Application Name in Task Manager

### ISSUE THREAD

**Issue by NicoNet** [Storj/farmer-gui#189]
The application name shown in Task Manager is confusing 
"Earn money by sharing your extra hard drive space (32-bit)"
It doesn't really tell you what the application is.
Would be better reading something like:
"DriveShare is Running"
"DriveShare is Stopped"
![2016-02-25](https://cloud.githubusercontent.com/assets/123434/13325678/d515e5e8-dbb0-11e5-8dd4-7ca3ce40bcb3.png)

**Comment by super3** [comment]
Yeah that does seem pretty long and wordy. Will fix.

**Comment by gordonwritescode** [comment]
This is getting pulled from the `package.json`'s `description` property. Seems this only affects Windows. I'm going to to close as it's not really an issue.

**Comment by bryanchriswhite** [comment]
FWIW this also effects the windows firewall app list:
![windows firewall](https://cloud.githubusercontent.com/assets/600733/16364546/18606c9e-3bea-11e6-9755-edbce87eae5f.PNG)
