### ISSUE TITLE
self report has more free space than available on my drive

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer-gui#197]
Open farmer-gui and let it farm with 100TB. I don't have that much space available but farmer-gui self report sends 100TB free space to the server.

**Comment by gordonwritescode** [comment]
I know this is no good, but it *is* a "self-report" and thus we are relying on an honor system. We are not currently using the metrics for farmer selection in bridge, so I'm going to close. Once the network is live we won't collect telemetry reports this way.
