### ISSUE TITLE
Message signature expired and RPC timeout

### ISSUE THREAD

**Issue by MidgetMob** [Storj/farmer-gui#198]
Attempting to start farmer-gui v0.6.0 results in the following errors and warnings:

> **{info}** [Mon Apr 11 2016 02:04:30 GMT-0400 (Eastern Daylight Time)]
> node created with nodeID bba1b6aa1820283506a8d99f69fb0211b73ea392
> **{info}** [Mon Apr 11 2016 02:04:30 GMT-0400 (Eastern Daylight Time)]
> subscribing to topic "01020202"
> **{info}** [Mon Apr 11 2016 02:04:30 GMT-0400 (Eastern Daylight Time)]
> subscribing to topic "02020202"
> **{info}** [Mon Apr 11 2016 02:04:30 GMT-0400 (Eastern Daylight Time)]
> subscribing to topic "03020202"
> **{warn}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> could not connect to NAT device via UPnP
> **{info}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> attempting to open connection tunnel...
> **{info}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> established tunnel, you are: http://bba1b6aa.tunnel.metadisk.org
> **{info}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> sending FIND_NODE message to {"protocol":"0.5.2","address":"api.metadisk.org","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1460354672295}
> **{info}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> received valid message from {"protocol":"0.5.2","address":"api.metadisk.org","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1460354672406}
> **{error}** [Mon Apr 11 2016 02:04:32 GMT-0400 (Eastern Daylight Time)]
> Message signature expired
> **{warn}** [Mon Apr 11 2016 02:04:40 GMT-0400 (Eastern Daylight Time)]
> rpc call e1189bd374dfa2fdd51f3c6d56d7640c1688c254 timed out
> **{warn}** [Mon Apr 11 2016 02:04:40 GMT-0400 (Eastern Daylight Time)]
> query failed, removing contact for shortlist, reason RPC with ID `e1189bd374dfa2fdd51f3c6d56d7640c1688c254` timed out

No shards are being generated however the gui reports that Storjfarmer is running.

**Comment by littleskunk** [comment]
synchronise your clock please

**Comment by MidgetMob** [comment]
Interesting, the time was correct and didn't change after toggling 'Set time automatically' but you seem to be right. Apologies and thanks.
