### ISSUE TITLE
Unable to start farming, error message EACCES 0.0.0.0:61755

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer-gui#200]
On windows 8 and windows server 2012 the gui doesn't start farming. It crash with EACCES error message.

![storj error](https://cloud.githubusercontent.com/assets/6333390/14426156/181f0dbe-ffed-11e5-856c-1b49475ca87c.PNG)

![pasted image at 2016_04_11 12_24 pm](https://cloud.githubusercontent.com/assets/6333390/14426163/2953c0b6-ffed-11e5-9919-08046d446aa9.png)

It is working fine on windows 10

**Comment by littleskunk** [comment]
I try to reproduce this error. I installed windows 8.0 32bit as virtualbox vm. I disabled windows updates and used the windows firewall to block the gui. Everything is working fine for me.

It must be something else. What else do you have? Any firewall, virusscanner or something like that?
My router doesn't support UPNP. Maybe you have an UPNP router?

**Comment by littleskunk** [comment]
Installed Kaspersky and everything is running fine. Slack user ayrat diabled UPNP and nothing changed.

Any other ideas?

**Comment by littleskunk** [comment]
slack user hdd:
I have Free AVG and just windows firewall. I just installed it and when it first launched windows firewall asked if I should allow it (which I did). I then added each drive one at a time, starting them as I went.
I am also running the gui version.
My computer is connected with Ethernet as well, no wifi.

**Comment by littleskunk** [comment]
I installed farmer cli on windows. I disabled NAT traversal and set my 127.0.0.1 as ip address. Time to start storjfarm. The command line asks for my password. I don't enter it and open resmon.exe to see the open ports. The app is not running but I have ~10 open ports.

```
Prozess	PID	Adresse	Port	Protokoll	Firewallstatus
node.exe	6096	fe80::58c7:9c30:c90b:9873	50253	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	192.168.56.1	50254	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	2003:84:ab7b:cb7c:7d2e:71cd:5c80:7604	50255	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	fd8e:746a:1d9b:1:7d2e:71cd:5c80:7604	50256	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	2003:84:ab7b:cb7c:7d34:6a60:c8d0:dac5	50257	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	2003:84:ab7b:cb7c:dca7:33dd:198d:2ed7	50258	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	fd8e:746a:1d9b:1:7d34:6a60:c8d0:dac5	50259	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	fd8e:746a:1d9b:1:dca7:33dd:198d:2ed7	50260	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	fe80::7d2e:71cd:5c80:7604	50261	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	192.168.123.103	50262	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	2001:0:9d38:90d7:cd1:bda:a842:8808	50263	UDP	Zulässig, nicht eingeschränkt
node.exe	6096	fe80::cd1:bda:a842:8808	50264	UDP	Zulässig, nicht eingeschränkt
```

Note: I have 7 IPv6 address cause of virtualbox.

@gordonwritescode Can you fix this? I would expect one open port.

**Comment by gordonwritescode** [comment]
Okay, I tracked this down to the use of a module called `portastic`, which the farmer uses to look for an open port to use if none is supplied (selecting randomly within a range).

It looks like the `portastic` module does this by actually [creating a TCP server and binding it to a port](https://github.com/alanhoff/node-portastic/blob/master/lib/portastic.js), then closing it to check if it's open. Looks like in the case of an error like this, it doesn't clean up after itself. 

This is no good, I agree. I will remove the use of it in the next version.

**Comment by ThorvaldAagaard** [comment]
I am getting this error on Windows 10, it did work about a week ago, now it no longer works. I have made no software update since last wime it worked

**Comment by gordonwritescode** [comment]
Portastic removed from Storj/core@0.6.0 - imminent Farmer GUI release will resolve this

**Comment by littleskunk** [comment]
@gordonwritescode are you sure? resmon.exe shows me ~20 open ports for storjfarmer-gui

StorjFarmer Version 0.7.0 
Protocol Version 0.6.0

**Comment by gordonwritescode** [comment]
Hm, well I'm sure that it's not related to anything we are doing. However, I'm wondering if some of the open ports (or all of them) are opened by electron itself. https://github.com/electron/electron/issues/5014

Maybe the IPC interface uses them? I don't know enough about how electron's IPC works, but I do know that Storj will open **1** port for RPC server to receive messages from the network + if tunneling, **1** more for tunnel server, then **1** for every active tunnel that is established.

**Comment by littleskunk** [comment]
You are right. Fix confirmed. User are happy now.
