### ISSUE TITLE
Error message: Failed to find tunnels

### ISSUE THREAD

**Issue by FloGerlich** [Storj/farmer-gui#209]
I've just upgraded to V0.7.1, and when starting up my 2 drives, I get the following error:
"failed to find tunnels, reason: RPC with ID '123412341234......' timed out".
No idea what to do.

**Comment by robertodijo** [comment]
Same here. I am also getting a similar error.
I think this issue is related to https://github.com/Storj/farmer-gui/issues/205

**Comment by littleskunk** [comment]
duplicate: https://github.com/Storj/farmer-gui/issues/205
