### ISSUE TITLE
unable to establish tunnel

### ISSUE THREAD

**Issue by FelizLuz** [Storj/farmer-gui#213]
Storj Share Version 0.7.4
Protocol version 0.6.7

```{info} [Fri Apr 29 2016 16:44:31 GMT-0700 (Pacific Daylight Time)]
node created with nodeID a83c380bb0e553e215cffa0b81ae57fecf716a65
{info} [Fri Apr 29 2016 16:44:31 GMT-0700 (Pacific Daylight Time)]
requesting probe from nearest neighbor
{info} [Fri Apr 29 2016 16:44:31 GMT-0700 (Pacific Daylight Time)]
sending PROBE message to {"protocol":"0.6.7","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461973471757}
{warn} [Fri Apr 29 2016 16:44:32 GMT-0700 (Pacific Daylight Time)]
could not connect to NAT device via UPnP
{info} [Fri Apr 29 2016 16:44:32 GMT-0700 (Pacific Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.7","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461973472010}
{warn} [Fri Apr 29 2016 16:44:51 GMT-0700 (Pacific Daylight Time)]
rpc call b54a8cf35e5aeff486586555c3ccef3be7c8792d timed out
{info} [Fri Apr 29 2016 16:44:51 GMT-0700 (Pacific Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Fri Apr 29 2016 16:44:51 GMT-0700 (Pacific Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.7","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461973491756}
{warn} [Fri Apr 29 2016 16:44:51 GMT-0700 (Pacific Daylight Time)]
rpc call f3b6fd45c20913fcfe50e0d589a160aa52509a74 timed out
{warn} [Fri Apr 29 2016 16:44:51 GMT-0700 (Pacific Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `f3b6fd45c20913fcfe50e0d589a160aa52509a74` timed out
{warn} [Fri Apr 29 2016 16:45:11 GMT-0700 (Pacific Daylight Time)]
rpc call 5e363b86b16029715d490db4e82e349d6983371e timed out
{warn} [Fri Apr 29 2016 16:46:32 GMT-0700 (Pacific Daylight Time)]
missing or empty reply from contact
{warn} [Fri Apr 29 2016 16:46:32 GMT-0700 (Pacific Daylight Time)]
missing or empty reply from contact
{warn} [Fri Apr 29 2016 16:46:52 GMT-0700 (Pacific Daylight Time)]
missing or empty reply from contact
 STORJ SHARE IS RUNNING```

**Comment by FloGerlich** [comment]
I have the same problem. 
error message says: failed to establish tunnel, reason: no tunnelers were returned.

**Comment by MidgetMob** [comment]
I get the same thing as well. I've synced the clock however the rpc call timeouts, missing/empty replies, and the message boxes still pop up with the "no tunnelers returned" message.

If it matters at all, I do get a "could not connect to NAT device via UPnP" warn when starting the client.

**Comment by pvdl** [comment]
I got this problem too.
Upgraded from 0.5.x release to 0.7.4.
Linux Mint 17.3
I even removed completely the Storj and configuration settings and reinstalled it again.
"could not connect to NAT device via UPnP"
and
"missing or empty reply from contact"
"rpc call xxx timed out"

**Comment by littleskunk** [comment]
Slack user br3nn88 found one reason for failed tunnel connection. Please make sure your system clock is synchronized with a good ntp server. That will not solve the problem for all of you but maybe a few are happy now.

**Comment by pvdl** [comment]
My clock is synced with a NTP server.
My solution was to enable the UPnP service on my modem. After enabling it, I didn't got timed out rpc calls any more.
Enabling UPnP is a security risk. I would prefer a good tutorial how to make a port forwarding for the Storj service.

**Comment by littleskunk** [comment]
@pvdl You should switch to https://github.com/Storj/farmer. The config wizard will ask you for the port. You can ask me on slack (http://slack.storj.io/) if you have any questions.

**Comment by gordonwritescode** [comment]
Closing. If it persists, please reopen at https://github.com/Storj/core/issues
