### ISSUE TITLE
System Tray icon on OS X 10.11.4 too big

### ISSUE THREAD

**Issue by JeremyPepper2** [Storj/farmer-gui#216]
<img width="177" alt="screen shot 2016-05-02 at 10 44 22 pm" src="https://cloud.githubusercontent.com/assets/11845884/14973576/92171302-10b7-11e6-806d-7dbcef6a2e8f.png">

As you can see, the tray icon is not displaying well.  It is not only slightly blurry (already reported - for Windows I believe), but also too big for a tray icon in OS X.

**Comment by littleskunk** [comment]
I moved your issue to https://github.com/Storj/farmer-gui/issues/161. Thank for reporting it.
