### ISSUE TITLE
Debian Package generates a symbolic link to a non existing folder and file

### ISSUE THREAD

**Issue by pvdl** [Storj/farmer-gui#217]
When I install the .deb package (version 0.7.4), a symbolic link is created to a non existing folder and file:

Look in the folder: ls -l /usr/local/bin
You find this symbolic link:
lrwxrwxrwx 1 root root   26 May  3 21:38 driveshare -> /opt/driveshare/driveshare

The file DEBIAN/postinst in the .deb package is responsible for creating this symbolic link

**Comment by gordonwritescode** [comment]
woopsie - didn't get updated with the rename commit here: https://github.com/Storj/farmer-gui/commit/f2fbfa871111acc7e181f74edd223b362ddb97ed

**Comment by pvdl** [comment]
I just removed this symbolic link afterwards in the /usr/local/bin folder.

**Comment by littleskunk** [comment]
Will be fixed with 0.7.5

**Comment by littleskunk** [comment]
Linux GUI binary 0.7.5 has a new installation directory. You will have to remove 0.7.4 yourself (`/opt/storj-farmer-gui` and `/usr/local/bin/driveshare`)
