### ISSUE TITLE
Estimate Rewards

### ISSUE THREAD

**Issue by super3** [Storj/farmer-gui#72]
We currently calculate test group payments to users every two weeks to a month. We do this by collecting uptime, space, etc. over time for each user and then calculating a users relative performance to the network from the data to get a final payout. 

There is an API exposed to do this for each user calculated daily: http://graph.driveshare.org/api/summary/15i4WvYn5KM5WupuCfQQvdTyHkXE34v2DE

Using the information from the API, and knowing the rewards to be distributed you can calculate and display the estimated rewards in real time to the user. You do this by doing ```points/total_points``` for a particular user to get their percentage of the total rewards. 

Rewards increase linearly over time. So if 100k SJCX was supposed to be distributed in a month you would create a linear function ```current_user_rewards = rewards for the month * (current_time/month) * user_percentage```. This should allow the user to see their estimated rewards go up every few seconds on the interface.

**Comment by super3** [comment]
@gamedevsam Update?

**Comment by super3** [comment]
@gordonwritescode Moving this to 0.7, but I'd like to have it done before then. Does it affect our core business? No. But it answers the question that is asked at least 3 times a day.

**Comment by gordonwritescode** [comment]
I removed the milestone due to lack of movement or communication on the issue. Milestones should track issues that have been triaged and discussed so that we can accurately plan releases.

**Comment by gordonwritescode** [comment]
Read: do we need to reassign this from @gamedevsam to myself or @mrfancymonocle?

**Comment by super3** [comment]
Let discuss 0.6 and 0.7 milestones in their entirety tomorrow.

**Comment by gordonwritescode** [comment]
:+1:

**Comment by super3** [comment]
I've made a calendar invite just to make sure we block out time

**Comment by belisards** [comment]
hey @super3 i'm trying to visualize the rewards using the API that you sent, but I can't see nothing. In my DriveShare, my balance still zero... 

how could I see the rewards?

**Comment by littleskunk** [comment]
@belisards This issue has the feature label. It is a issue for the devs. Please keep it clear. Please don't use it for FAQ. If you have any question you can ask on slack. If you think your question is importend you can open a new github issue. One closed issue more or less is not a problem for the devs as long as there own issues are clear.

Read the FAQ on the bottom of the page http://driveshare.org/rewards.html. There is the link to the last reward list. Look for your payout address. I hope to see you in slack for anything else :)

**Comment by belisards** [comment]
sorry, the slack was down yesterday. i will delete my first post and then this one, ok?

**Comment by gordonwritescode** [comment]
The closer we get to production the less meaningful this becomes. We won't be able to accurately estimate earnings as it will be based on the market. We can estimate payouts from bridge, but farmer-gui is not tied to bridge, so I'm not sure this should be an objective anymore.
